name: Password Strength Meter
author: Virtuosi Media
category: Forms
tags: [password, user-interface, security]
docs: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/password-strength-meter/password-strength-meter-api-documentation
demo: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/password-strength-meter/password-strength-meter-demos
current: 1.0